# Generated by Django 6.0.7 on 2026-08-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order_name',
            field=models.CharField(blank=True, help_text="Optional. The seller's own name for this product, for use when ordering.", max_length=200),
        ),
    ]
