# Generated by Django 6.0.7 on 2026-08-05 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_product_order_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Current price in euros. Leave empty if not known.', max_digits=10, null=True),
        ),
    ]
